<a href="https://colab.research.google.com/github/Only-Eni/Google-Developers-Group-Campus/blob/main/GDG_AI_DAY_9_NUMPY_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Model Evaluation – Regression Metrics

In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

print("All necessary libraries and modules imported successfully.")

All necessary libraries and modules imported successfully.

In [39]:
df = pd.read_csv('data.csv')
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [40]:
df.describe()
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [41]:
# Define X (features) and y (target)

X = df[["Duration", "Pulse", "Maxpulse"]]
y = df["Calories"]

X.head()

   Duration  Pulse  Maxpulse
0        60    110       130
1        60    117       145
2        60    103       135
3        45    109       175
4        45    117       148

In [45]:
X = pd.get_dummies(X, drop_first=True)

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [47]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [48]:
y_pred = model.predict(X_test)

In [49]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

In [54]:
mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)

mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

rmse = np.sqrt(mse)
print("RMSE:", rmse)

MAE: 70.3888350519852
MSE: 6739.37946553489
RMSE: 82.09372366712871

## Model Evaluation Summary (Fitness Dataset)

The model was evaluated using MAE, MSE, and RMSE.

- MAE shows the average calorie prediction error per workout.
- RMSE indicates the typical magnitude of prediction error.
- If RMSE is close to MAE, errors are fairly consistent.
- If RMSE is much larger than MAE, the model makes some large mistakes.


##The model provides a reasonable prediction performance.